name: iOS CD

on:
  pull_request:
    branches:
      - develop
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-15
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GIT_AUTHORIZATION || secrets.GITHUB_TOKEN }}
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: Madabank
          
      - name: Install dependencies
        working-directory: Madabank
        run: |
          tuist install
          bundle install
        
      - name: Generate project
        working-directory: Madabank
        run: tuist generate
        
      - name: Run Fastlane Beta
        working-directory: Madabank
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
        run: bundle exec fastlane beta
